config/routes.rb
Rails.application.routes.draw do
	root to: 'pages#home'

	resources :projects, only: [:index]
	resources :brands, only: [:index]

	get 'show1', to: 'projects#show1'
	get 'show2', to: 'projects#show2'
	get 'show3', to: 'projects#show3'  
	get 'show4', to: 'projects#show4'

	get 'blog', to: 'blogs#show'
	get 'blog1', to: 'blogs#show1'
	get 'blog2', to: 'blogs#show2'
	get 'blog3', to: 'blogs#show3'
	get 'blog4', to: 'blogs#show4'
	get 'blog5', to: 'blogs#show5'
	get 'blog6', to: 'blogs#show6'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

	def show
	end

	def show1
	end

	def show2

	end

	def show3
	end

	def show4
	end

	def show5
	end

	def show6
		
	end


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show1

  end	

  def show2

  end

  def show3
  end

  def show4
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/show.html.erb
show.html.erb

app/views/blogs/show1.html.erb
show1.html.erb

app/views/blogs/show2.html.erb
show2.html.erb

app/views/blogs/show3.html.erb
show3.html.erb

app/views/blogs/show4.html.erb
show4.html.erb

app/views/blogs/show5.html.erb
show5.html.erb

app/views/blogs/show6.html.erb
show6.html.erb

app/views/brands/index.html.erb
<%=render 'layouts/navbar' %>
<section id="banner">
	<div class="banner-image-project">
		<div>
			<h1 class="header-1 ">MARJOLIJN BIJMAN</h1>
			<h2>INTERIOR ARCHITECT</h2>
		</div>
		<i class="fa fa-bars fa-2x" id="logo-bar"></i>
	</div>
</section>

<div class="wrapper">
	<div class="title">
		<h2 class="text-center">Brands</h2>
	</div>
	<div class="description text-center">
		<p>Discover my favorite brands & partners</p>
	</div>
	<div class="container text-center">
		<div class="row text-center ">
			<div class="col-xs-12 col-md-6 space-between">
			<div class="card-img center-block" >
					<%=link_to 'http://www.normann-copenhagen.com/', target:'_blank' do %>
					<%=image_tag("normann-logo.png",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
			<div class="col-xs-12 col-md-6 space-between">
				<div class="card-img center-block">
					<%=link_to 'http://www.muuto.com/', target:'_blank' do %>
					<%=image_tag("muuto.png",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>

		</div>
		<div class="row">
			<div class="col-xs-12 col-md-4 space-between">
				<div class="card-img center-block" >
					<%=link_to 'http://www.fermliving.com//', target:'_blank' do %>
					<%=image_tag("fermliving.png",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
			<div class="col-xs-12 col-md-4 space-between">

				<div class="card-img faro center-block" >
					<%=link_to 'http://eu.farrow-ball.com/', target:'_blank' do %>
					<%=image_tag("farrow & ball.jpg",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
			<div class="col-xs-12 col-md-4 space-between">
				<div class="card-img vola center-block" >
					<%=link_to 'http://en.vola.com/', target:'_blank' do %>
					<%=image_tag("VOLA.png",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-12 col-md-6 space-between">
				<div class="card-img center-block" >
					<%=link_to 'http://www.weverducre.com/en/Home', target:'_blank' do %>
					<%=image_tag("wever-ducre.png",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
			<div class="col-xs-12 col-md-6 space-between">
				<div class="card-img center-block" >
					<%=link_to 'http://www.fierenskeukens.be/', target:'_blank' do %>
					<%=image_tag("fierens-logo.jpg",class: "img-responsive center-block") %>
					<% end %>
				</div>
			</div>
		</div>
	</div>

</div>





<%=render 'layouts/footer'  %>	

app/views/layouts/_carousel.html.erb
 <div id="carousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag "banner1.jpg" %>
          <div class="carousel-caption">
            <h3>test</h3>
          </div>
        </div>
        <div class="item">
          <%= image_tag "banner2.jpg"%>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "banner3.jpg"%>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag "banner7.jpg"%>
          <div class="carousel-caption">
          </div>
        </div>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

app/views/layouts/_footer.html.erb
<section id="contact">
  <div class="wrapper-black"></div>
  <div class="wrapper-contact">
    <div class="container">
      <div class="row contact-content">
        <div class="col-xs-12">
          <h2 class="contact">CONTACT</h2>
          <p> Marjolijn Bijman Interior Architect</p>
          <ul class= "fa-ul">
            <li class="email"><i class="fa fa-envelope-o" aria-hidden="true"></i> marjolijnbijman@gmail.com - </li>
            <li><i class="fa fa-volume-control-phone" aria-hidden="true"></i> (+32) 489635823 -</li>
            <li class="adress"> Rue general patton 33 - 1050 - Ixelles - Belgium</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper-black">
  <div class="copyright">
      <i class="fa fa-copyright"><b&n> Michael Hanot Allright Reserved</i>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<section id="navbar">
<i id="cross"class="fa fa-times"></i>
<div>
<div id="link-home">
<%= link_to "HOME", root_path(anchor: "banner") %>
</div>

<div id="link-about">
<%= link_to "ABOUT", root_path(anchor: "about") %>
</div>

<div id="link-project">
<%= link_to "PROJECTS", root_path(anchor: "work") %>
</div>

<div id="link-brand">
<%= link_to "BRANDS", root_path(anchor: "brand") %>
</div>

<div id="link-inspiration">
	<%= link_to "INSPIRATION", root_path(anchor: "inspiration") %>

</div>

<div id="link-contact">
	<%= link_to "CONTACT", root_path(anchor: "contact") %>
</div>

</div>
</section>

app/views/layouts/_site.html.erb
<section id="navbar">
<i id="cross"class="fa fa-times"></i>
<div>
<div>HOME</div>
<div>ABOUT</div>
<div>PROJECT</div>
<div>BRAND</div>
<div>JOURNAL</div>
<div>INSPIRATION</div>
<div>CONTACT</div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
   <%=render 'layouts/navbar'  %>

   <section id="site" class="active">
    <section id="banner">  
      <div class="wrapper-home">
        <div class="banner-image">
          <div>
            <h1 class="header-1">MARJOLIJN BIJMAN</h1>
            <h2>INTERIOR ARCHITECT</h2>
          </div>

          <%= link_to "#about-top" do %>
          <i class="fa fa-angle-down fa-5x smooth-scroll"></i>
          <% end %>
          <i class="fa fa-bars fa-2x" id="logo-bar"></i>
        </div>
      </div>
    </section>

    <section id="about-top">
      <div class="wrapper-about" id="about">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <h3 class="titre-about">dear.....</h3>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <p>architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam volup.</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur</p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo vo </p>
              <p>voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas </p>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui rfatione ni dolores eos qui </p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui rfatione ni dolores eos qui </p>
              <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremqu questions </p>
              <p></p>
              <p class="thanks">Thanks for reading.</p>
              <p class="greeting">
                Sincerely,
                <br>
                <em>duddksied
                  <em>
                    omnis toemas
                  </em>
                </em>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>


    <section id="work">
      <div class="wrapper-work">
        <div class="project-image">
          <div class="project">
            <h2 class="title-projects">PROJECTS</h2>
            <%= link_to "Curious? Click here", projects_path, class:"button-project"%>
          </div>
        </div>
      </div>
    </section>


    <section id="brand">
      <div class="wrapper-brand">
        <div class="brand-content">
          <div>
            <%=link_to brands_path do %>
            <h2 class='title-brand'>
              BRANDS</h2>
              <% end %>
              <p>Here will you find a selection of my favorite brand. Choosing the right partner to build your interior is also part of the succes</p>
            </div>
          </div>
        </div>
      </section>

      <hr>

      <section id="inspiration">
        <div class="blog-title">
          <h2>INSPIRATION</h2>
        </div>
        <div class="container blog-container">
          <div class="row">
            <div id="blog-grid">
              <div class="grid-sizer"></div>

              <div class="card card-long">
                <%= link_to "root_path", data: {toggle: "modal", target:"#myModal1"} do %>
                <%=image_tag "banner1.jpg", class:'long'%>
                <div class="blog-caption">
                </div>
                <% end %>
              </div>

              <div class="card card-square">
                <%= link_to "root_path", data: {toggle: "modal", target:"#myModal2"} do %>
                <%=image_tag "banner2.jpg", class:'square'%>
                <div class="blog-caption">
                </div>
                <% end %>
              </div>

              <div class="card card-square square2">
                <%= link_to "root_path", data: {toggle: "modal", target:"#myModal3"}  do %>
                <%=image_tag "banner3.jpg", class:'square'%>
                <div class="blog-caption">
                </div>
                <% end %>
              </div>

              <div class="card card-square square3">
               <%= link_to "root_path", data: {toggle: "modal", target:"#myModal4"} do %>
               <%=image_tag "banner3.jpg", class:'square'%>
               <div class="blog-caption">
               </div>
               <% end %>

             </div>

             <div class="card card-square square4">
              <%= link_to "root_path", data: {toggle: "modal", target:"#myModal5"} do  %>
              <%=image_tag "banner7.jpg", class:'square'%>
              <div class="blog-caption">
              </div>
              <% end %>
            </div>

            <div class="card card-large">
              <%= link_to "root_path", data: {toggle: "modal", target:"#myModal6"} do  %>
              <%=image_tag "banner9.jpg", class:'large'%>
              <div class="blog-caption">
              </div>
              <% end %>
            </div>

            <div class="card card-long-horizontal">
             <%= link_to "root_path", data: {toggle: "modal", target:"#myModal7"} do  %>
             <%=image_tag "project3.jpg", class:'horizontal'%>
             <div class="blog-caption">
             </div>
             <% end %>
           </div>

         </div>
       </div>
     </div>
   </section>

   <%=render 'layouts/footer'  %>
   <%=render 'layouts/modal' %>
 </section>

app/views/projects/index.html.erb
<%=render 'layouts/navbar' %>
<section id="banner">
	<div class="banner-image-project">
		<div>
			<h1 class="header-1 ">MARJOLIJN BIJMAN</h1>
			<h2>INTERIOR ARCHITECT</h2>
		</div>
		<i class="fa fa-bars fa-2x" id="logo-bar"></i>
	</div>
</section>

<section class='projects'>
	<div class="wrapper">
		<div class="container">
			<div class="row space-between">
				<div class="col-xs-12 col-md-6 text-left">
					<div class="card-project">
						<%= link_to show1_path do %>
						<%=image_tag "banner2.jpg", {class:'img-project'} %>
						<%end %>
					</div>
					<div class="text-project">
						<p>ttexlokfkfk</p>
					</div>
					<div class="button-see-more text-center">
						<%=link_to "SEE MORE", show1_path,class: "black-button" %>
					</div>

				</div>

				<div class="col-xs-12 col-md-6">
					<div class="card-project">
						<%=link_to show2_path do  %>
						<%=image_tag "banner3.jpg", {class:'img-project'} %>
						<% end %>
					</div>
					<div class="text-project">
						<p>test test test test</p>
					</div>
					<div class="button-see-more text-center">
						<%=link_to "SEE MORE", show2_path,class: "black-button" %>
					</div>
				</div>
			</div>

			<div class="row space-between">
				<div class="col-xs-12 col-md-6 text-left">
					<div class="card-project">
						<%=link_to show3_path  do %>
						<%=image_tag "banner8.jpg", {class:'img-project'} %>
						<% end %>
					</div>
					<div class="text-project">
						<p>ttexlokfkfk</p>
					</div>
				<div class="button-see-more text-center">
					<%=link_to "SEE MORE", show3_path,class: "black-button" %>
				</div>
				</div>

				<div class="col-xs-12 col-md-6">
					<div class="card-project">
						<%= link_to show4_path do %>	
						<%=image_tag "banner9.jpg", {class:'img-project'} %>
						<% end %>
					</div>
					<div class="text-project">
						<p>test test test test</p>
					</div>
					<div class="button-see-more text-center">
						<%=link_to "SEE MORE", show4_path,class: "black-button" %>
					</div>
				</div>
			</div>


		</div>
	</div>
</section>

<section class=space-footer>
	<%=render 'layouts/footer'  %>
</section>

app/views/projects/show1.html.erb
	<%=render 'layouts/navbar' %>
	<section id="banner">
		<div class="banner-image-project">
			<div>
				<h1 class="header-1 ">MARJOLIJN BIJMAN</h1>
				<h2>INTERIOR ARCHITECT</h2>
			</div>
			<i class="fa fa-bars fa-2x" id="logo-bar"></i>
		</div>
	</section>
	

	<div class="wrapper">
		<div class="container">
			<h1 class="space-between-title">Title project</h1>
			<div class="space-between-title" >
				<%=link_to "BACK", projects_path,class: "black-button" %>
			</div>
			<div class="row show-project ">
				<div class="col-xs-12 col-md-4">
					<h2 class="space-between-title">test</h2>
					<p><%=Faker::Lorem.paragraph(sentence_count = 8)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 7)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 6)%></p>
				</div>
				<div class="col-xs-12 col-md-8">
					<div class="image-project">
						<%=image_tag "banner2.jpg", {class:'img-large'} %>
					</div>
				</div>
			</div>


			<div class="row show-project text-center">
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner3.jpg", {class:'img-small'} %>
					</div>
				</div>
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner7.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner9.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner8.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project1.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project3.jpg", {class:'img-small'} %>
					</div>
				</div>

			</div>
		</div>
	</div>

	<%=render 'layouts/footer'%>	

app/views/projects/show2.html.erb
	<%=render 'layouts/navbar' %>
	<section id="banner">
		<div class="banner-image-project">
			<div>
				<h1 class="header-1 ">MARJOLIJN BIJMAN </h1>
				<h2>INTERIOR ARCHITECT</h2>
			</div>
			<i class="fa fa-bars fa-2x" id="logo-bar"></i>
		</div>
	</section>
	

	<div class="wrapper">
		<div class="container">
			<h1 class="space-between-title">Title project</h1>
			<div class="space-between-title" >
				<%=link_to "BACK", projects_path,class: "black-button" %>
			</div>
			<div class="row show-project ">
				<div class="col-xs-12 col-md-4">
					<h2 class="space-between-title">test</h2>
					<p><%=Faker::Lorem.paragraph(sentence_count = 8)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 7)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 6)%></p>
				</div>
				<div class="col-xs-12 col-md-8">
					<div class="image-project">
						<%=image_tag "banner2.jpg", {class:'img-large'} %>
					</div>
				</div>
			</div>


			<div class="row show-project text-center">
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner3.jpg", {class:'img-small'} %>
					</div>
				</div>
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner7.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner9.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner8.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project1.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project3.jpg", {class:'img-small'} %>
					</div>
				</div>

			</div>
		</div>
	</div>

	<%=render 'layouts/footer'%>	

app/views/projects/show3.html.erb
	<%=render 'layouts/navbar' %>
	<section id="banner">
		<div class="banner-image-project">
			<div>
				<h1 class="header-1 ">MARJOLIJN BIJMAN </h1>
				<h2>INTERIOR ARCHITECT</h2>
			</div>
			<i class="fa fa-bars fa-2x" id="logo-bar"></i>
		</div>
	</section>
	

	<div class="wrapper">
		<div class="container">
			<h1 class="space-between-title">Title project</h1>
			<div class="space-between-title" >
				<%=link_to "BACK", projects_path,class: "black-button" %>
			</div>
			<div class="row show-project ">
				<div class="col-xs-12 col-md-4">
					<h2 class="space-between-title">test</h2>
					<p><%=Faker::Lorem.paragraph(sentence_count = 8)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 7)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 6)%></p>
				</div>
				<div class="col-xs-12 col-md-8">
					<div class="image-project">
						<%=image_tag "banner2.jpg", {class:'img-large'} %>
					</div>
				</div>
			</div>


			<div class="row show-project text-center">
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner3.jpg", {class:'img-small'} %>
					</div>
				</div>
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner7.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner9.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner8.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project1.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project3.jpg", {class:'img-small'} %>
					</div>
				</div>

			</div>
		</div>
	</div>

	<%=render 'layouts/footer'%>	

app/views/projects/show4.html.erb
	<%=render 'layouts/navbar' %>
	<section id="banner">
		<div class="banner-image-project">
			<div>
				<h1 class="header-1 ">MARJOLIJN BIJMAN </h1>
				<h2>INTERIOR ARCHITECT</h2>
			</div>
			<i class="fa fa-bars fa-2x" id="logo-bar"></i>
		</div>
	</section>
	

	<div class="wrapper">
		<div class="container">
			<h1 class="space-between-title">Title project</h1>
			<div class="space-between-title" >
				<%=link_to "BACK", projects_path,class: "black-button" %>
			</div>
			<div class="row show-project ">
				<div class="col-xs-12 col-md-4">
					<h2 class="space-between-title">test</h2>
					<p><%=Faker::Lorem.paragraph(sentence_count = 8)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 7)%></p>
					<p><%=Faker::Lorem.paragraph(sentence_count = 6)%></p>
				</div>
				<div class="col-xs-12 col-md-8">
					<div class="image-project">
						<%=image_tag "banner2.jpg", {class:'img-large'} %>
					</div>
				</div>
			</div>


			<div class="row show-project text-center">
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner3.jpg", {class:'img-small'} %>
					</div>
				</div>
				<div class="col-xs-12 col-md-6">
					<div class="image-project">
						<%=image_tag "banner7.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner9.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "banner8.jpg", {class:'img-small'} %>
					</div>
				</div>
			</div>

			<div class="row show-project text-center">
				<div class="col-xs-12">
					<p><%=Faker::Lorem.paragraph(sentence_count = 5)%></p>
				</div>
			</div>
			
			<div class="row show-project">
				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project1.jpg", {class:'img-small'} %>
					</div>
				</div>

				<div class="col-xs-12 col-md-6 text-center">
					<div class="image-project">
						<%=image_tag "project3.jpg", {class:'img-small'} %>
					</div>
				</div>

			</div>
		</div>
	</div>

	<%=render 'layouts/footer'%>	